version: '3.8'
services:
  skygge_validate-mysql:
    image: mysql:8.0.23
    # volumes:
    #     - ~/volumes/jhipster/skygge_validate/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=yourStrong(!)Password
      - MYSQL_DATABASE=skygge_validate
    ports:
      - 3307:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
